name: Build Release

on:
  workflow_dispatch:

jobs:
  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        config: [Release]
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        run: cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build
        run: cmake --build build --config ${{ matrix.config }}

      - name: Upload RE-UE4SS DLL and Mappings Generator
        uses: actions/upload-artifact@v4
        with:
          name: RE-UE4SS-Windows-Release
          path: |
            build/Output/Release/
            build/bin/Release/
            build/**/UE4SS.dll
            build/**/*.dll
            build/**/*.usmap
